default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  database: biome_<%= ENV.fetch("RAILS_ENV") %>

  host:     <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development: <<: *default
test: <<: *default
staging: <<: *default
production: <<: *default
