default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  database: biome_server_<%= Rails.env %>

  host:     <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development: 
  <<: *default
test: 
  <<: *default
staging: 
  <<: *default
production: 
  <<: *default
