# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9121553275175b25861a73bb2f3da41381362cb427ce1e9dd3d2445da5fac30a99ac464f0aadc1db32dcf94df8f170d11e04a557424a32ca6d89bd4fe614838

test:
  secret_key_base: 9f031d140cb7aa91bc09be8e45aebfa275856a6e61c622394da789f885c9dad14bfd3b4e8c78270b65eb4aebbf642908486701a2721fe2aa066b31eb7e070268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  carto_db:
    api_key: <%= ENV["CARTO_DB_API_KEY"] %>
    account: <%= ENV["CARTO_DB_ACCOUNT"] %>
    table: <%= ENV["CARTO_DB_TABLE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  carto_db:
    api_key: <%= ENV["CARTO_DB_API_KEY"] %>
    account: <%= ENV["CARTO_DB_ACCOUNT"] %>
    table: <%= ENV["CARTO_DB_TABLE"] %>

